fixtures:
  forge_modules:
    epel: "puppet/epel"
    python: "puppet/python"
    stdlib: "puppetlabs/stdlib"
    systemd: "puppet/systemd"
    yumrepo_core: "puppetlabs/yumrepo_core"
  symlinks:
    thumbor: "#{source_dir}"
